### ISSUE TITLE
HTTP connection example from Readme not working

### ISSUE THREAD

**Issue by mindreframer** [simia-tech/netx#2]
there seems to be no `github.com/simia-tech/netx/httpx` subpackage

**Comment by phifty** [comment]
Thanks for notice this. Should be working now.

**Comment by mindreframer** [comment]
thx for quick response! still not working! 

may you mean this: 

"net/http" instead of "http" ?

**Comment by mindreframer** [comment]
actually this is working: 

```
import (
  "net/http"
  "fmt"
  "io/ioutil"

  "github.com/simia-tech/netx"
  _ "github.com/simia-tech/netx/network/nats"
)
```

**Comment by mindreframer** [comment]
@phifty hey, you did it! 😸

**Comment by phifty** [comment]
Yeah thanks! I guess I got a bit too used to `goimports` :-)

**Comment by mindreframer** [comment]
closing the issue!
